import { expect, test } from "@playwright/test";
import { signInWithDefaultLayout } from "./workspace-fixtures";

test("three rows stay stable while menus open and patient context survives navigation", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await signInWithDefaultLayout(page, "Prototype provider");
  const header = (await page.locator(".topbar").boundingBox())!;
  const tools = (await page.locator(".tool-navigation").boundingBox())!;
  const tabs = (await page.locator(".browser-tabs").boundingBox())!;
  expect(tools.y).toBeGreaterThanOrEqual(header.y + header.height);
  expect(tabs.y).toBeGreaterThanOrEqual(tools.y + tools.height);
  await expect(page.locator(".dynamic-left-rail, .sidebar-drawer-trigger, .waffle-launcher")).toHaveCount(0);
  await page.screenshot({ path: "test-results/navigation-overview.png" });
  const maya = page.locator(".browser-tab[data-workspace-tab='patient']").filter({ hasText: "Maya Chen" });
  await maya.click();
  await page.getByRole("button", { name: "Clinical", exact: true }).click();
  await expect(page.getByRole("region", { name: "Clinical options" })).toBeVisible();
  expect((await page.locator(".browser-tabs").boundingBox())!.y).toBe(tabs.y);
  await page.getByRole("region", { name: "Clinical options" }).getByRole("button", { name: "Tasks", exact: true }).click();
  await expect(page.locator(".global-tasks-workspace")).toBeVisible();
  await expect(maya).toBeVisible();
  await page.getByRole("button", { name: "Clinical", exact: true }).click();
  await page.keyboard.press("Escape");
  await expect(page.locator(".tool-menu-panel")).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Clinical", exact: true })).toBeFocused();
  await expect(page.locator(".global-tasks-workspace")).toBeVisible();
  await maya.click();
  await expect(maya).toHaveClass(/active/);
  await expect(page.locator(".global-module-shell")).toHaveCount(0);
  await page.getByRole("button", { name: "Workspace", exact: true }).click();
  await expect(page.getByRole("region", { name: "Workspace options" })).toBeVisible();
  await page.getByRole("button", { name: "Clinical", exact: true }).click();
  await expect(page.getByRole("region", { name: "Workspace options" })).toHaveCount(0);
  await page.screenshot({ path: "test-results/navigation-desktop.png" });
});

test("tool menus support keyboard access and fit a narrow viewport", async ({ page }) => {
  await page.setViewportSize({ width: 640, height: 900 });
  await signInWithDefaultLayout(page, "Prototype provider");
  const clinical = page.getByRole("button", { name: "Clinical", exact: true });
  await clinical.focus();
  await page.keyboard.press("ArrowDown");
  const panel = page.getByRole("region", { name: "Clinical options" });
  await expect(panel.getByRole("button", { name: "Patients", exact: true })).toBeFocused();
  await page.keyboard.press("ArrowDown");
  await expect(panel.getByRole("button", { name: "Tasks", exact: true })).toBeFocused();
  await page.keyboard.press("Escape");
  await expect(clinical).toBeFocused();
  await page.getByRole("button", { name: "Practice", exact: true }).click();
  const box = (await page.getByRole("region", { name: "Practice options" }).boundingBox())!;
  expect(box.x).toBeGreaterThanOrEqual(0);
  expect(box.x + box.width).toBeLessThanOrEqual(640);
  await expect(page.getByRole("region", { name: "Practice options" }).getByRole("button", { name: "Reports" })).toHaveCount(0);
  await page.screenshot({ path: "test-results/navigation-narrow.png" });
  await page.getByRole("button", { name: "Home Launchpad" }).click();
  await expect(page.getByRole("textbox", { name: "Ask AI or search the EHR" })).toBeVisible();
  await expect(page.locator(".tool-navigation")).toBeVisible();
  await page.getByRole("button", { name: "Preferences", exact: true }).click();
  const preferences = page.getByRole("dialog", { name: "Workspace Layout Preferences" });
  await expect(preferences).toBeVisible();
  await preferences.getByRole("button", { name: "Close", exact: true }).click();
  const account = page.getByRole("button", { name: /Account menu for/ });
  await expect(account).toBeVisible();
  await account.click();
  await expect(page.getByRole("menuitem", { name: "Help", exact: true })).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(account).toBeFocused();
  await page.screenshot({ path: "test-results/navigation-home.png" });
});
